steps:
  # Build Docker image for micro-service-1
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and Push micro-service-1'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/k8s-b00930528/cloud-k8/micro-service-1:latest'
      - './micro-service-1'
  
  # Build Docker image for micro-service-2
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and Push micro-service-2'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/k8s-b00930528/cloud-k8/micro-service-2:latest'
      - './micro-service-2'
  
  # Build Docker image for micro-service-3
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and Push micro-service-3'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/k8s-b00930528/cloud-k8/micro-service-3:latest'
      - './micro-service-3'

  # Push the Docker images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Images to Artifact Registry 1'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/k8s-b00930528/cloud-k8/micro-service-1:latest'
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Images to Artifact Registry 2'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/k8s-b00930528/cloud-k8/micro-service-2:latest'
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Images to Artifact Registry 3'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/k8s-b00930528/cloud-k8/micro-service-3:latest'
