steps:
  # Build Docker image for micro-service-1
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and Push micro-service-1'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/assignment-2-391412/sdp-assignment2/micro-service-1:latest'
      - './micro-service-1'
  
  # Build Docker image for micro-service-2
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and Push micro-service-2'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/assignment-2-391412/sdp-assignment2/micro-service-2:latest'
      - './micro-service-2'
  
  # Build Docker image for micro-service-3
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and Push micro-service-3'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/assignment-2-391412/sdp-assignment2/micro-service-3:latest'
      - './micro-service-3'

  # Push the Docker images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Images to Artifact Registry 1'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/assignment-2-391412/sdp-assignment2/micro-service-1:latest'
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Images to Artifact Registry 2'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/assignment-2-391412/sdp-assignment2/micro-service-2:latest'
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Images to Artifact Registry 3'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/assignment-2-391412/sdp-assignment2/micro-service-3:latest'

  # Deploy micro-service-1 to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'micro-service-1-instance'
      - '--image'
      - 'us-east1-docker.pkg.dev/assignment-2-391412/sdp-assignment2/micro-service-1:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'

  # Deploy micro-service-2 to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'micro-service-2-instance'
      - '--image'
      - 'us-east1-docker.pkg.dev/assignment-2-391412/sdp-assignment2/micro-service-2:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'

  # Deploy micro-service-3 to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'micro-service-3-instance'
      - '--image'
      - 'us-east1-docker.pkg.dev/assignment-2-391412/sdp-assignment2/micro-service-3:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'